services:
  - type: web
    name: miniprojet
    env: docker
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: deploy
      - key: DB_HOST
        fromDatabase:
          name: miniprojet-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: miniprojet-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: miniprojet-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: miniprojet-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: miniprojet-db
          property: password

databases:
  - name: miniprojet-db
    databaseName: miniprojet
    user: miniprojet
    plan: free
    region: frankfurt
